name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, win32]

    steps:
    - uses: actions/checkout@v3

    - name: build docker image
      run: docker build -t build .

    - name: prepare
      run: cd lib && make prepare && cd ..

    - name: build in docker image
      run: docker run -v $PWD:/work --rm build bash -c "cd /work && make ${{ matrix.os }}"

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: |
          ${{ matrix.os }}*.zip
          ${{ matrix.os }}*.tar.gz

  build_linux_explicit_lua:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: build docker image
      run: docker build -f Dockerfile.linux-linked -t build-linked .

    - name: prepare
      run: cd lib && make prepare-linux-linked

    - name: build in docker image
      run: docker run -v $PWD:/work --rm build-linked bash -c "cd /work && make linux-linked"

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-linked
        path: linux*-lua*-linked.tar.gz

  build_macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15-intel]

    steps:
    - uses: actions/checkout@v3

    - name: build
      run: make macos

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}
        path: macos*.tar.gz

  release:
    needs: [ build, build_linux_explicit_lua, build_macos ]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - name: download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifact
        merge-multiple: true

    - name: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh && bash upload.sh artifact/*
